name: Generate benchmarks

on: [push, pull_request]

# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    name: Generate benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - run: |
          cd benchmarks
          pwd
          go get -u -d 
          go mod tidy
          go test -bench . -benchmem > benchmarks.txt

      - run: echo $GITHUB_SHA
      - name: Commit benchmarks
        uses: EndBug/add-and-commit@v7
        with:
          default_author: user_info
          message: "Benchmarks for $GITHUB_SHA"
          pull_strategy: NO-PULL
